# Generated by Django 2.2.10 on 2020-06-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ManyToManyField(related_name='get_posts', to='core.categoria'),
        ),
    ]
