# Generated by Django 2.2.10 on 2020-06-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='categoria',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
