# Generated by Django 3.0.4 on 2020-03-26 02:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AddField(
            model_name='page',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
