# Generated by Django 2.2.10 on 2021-01-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destacado',
        ),
    ]
