# Generated by Django 3.0.5 on 2020-04-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200325_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['orden'], 'verbose_name': 'pagina', 'verbose_name_plural': 'paginas'},
        ),
        migrations.AddField(
            model_name='page',
            name='orden',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
