# Generated by Django 2.2.10 on 2020-06-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200624_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
        migrations.AddField(
            model_name='page',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo de la Pagina en Index'),
        ),
    ]
