# Generated by Django 2.2.10 on 2020-06-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200624_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Activar para Destacar en Index'),
        ),
    ]
