# Generated by Django 2.2.10 on 2020-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('orden', models.SmallIntegerField(default=0)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destacado',
                'verbose_name_plural': 'Destacados',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='destacado',
        ),
        migrations.AlterField(
            model_name='page',
            name='orden',
            field=models.SmallIntegerField(default=0),
        ),
    ]
