# Generated by Django 2.2.10 on 2020-06-25 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200624_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='destacado',
            name='pagina',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Page'),
            preserve_default=False,
        ),
    ]
