# Generated by Django 2.2 on 2020-07-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200630_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='titulo',
        ),
    ]
