# Generated by Django 2.2 on 2020-07-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_page_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destacado',
            name='pagina',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Page'),
        ),
    ]
