# Generated by Django 2.2.10 on 2021-01-06 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='celular',
            new_name='phone',
        ),
    ]
