# Generated by Django 2.2 on 2020-06-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Apellido',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
