# Generated by Django 2.2 on 2020-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200626_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
