# Generated by Django 2.2 on 2020-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='celular',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Celular'),
        ),
    ]
