# Generated by Django 2.2.10 on 2021-09-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='categorias', verbose_name='Imagen de Presentación')),
                ('orden', models.IntegerField(default=5, verbose_name='Orden de Prioridades')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo de la Portada')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtitulo de la Portada')),
                ('precio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Precio del Título')),
                ('boton', models.CharField(default='Compre Ahora', max_length=20, verbose_name='Boton de la Portada')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='portadas', verbose_name='Imagen de Presentación')),
                ('orden', models.IntegerField(default=5, verbose_name='Orden de Prioridades')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portada',
                'verbose_name_plural': 'Portadas',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('precio_oferta', models.IntegerField(default=0, verbose_name='Precio Oferta')),
                ('imagen', models.ImageField(blank=True, upload_to='', verbose_name='Imagén')),
                ('orden', models.IntegerField(default=5, verbose_name='Orden de Prioridades')),
                ('oferta', models.BooleanField(default=False, verbose_name='En Oferta/Precio Normal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('categorias', models.ManyToManyField(related_name='get_categoria', to='productos.Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(default='', max_length=100, verbose_name='Modelo')),
                ('talle', models.CharField(default='', max_length=100, verbose_name='Talle')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'ordering': ['id'],
            },
        ),
    ]
