# Generated by Django 2.2.10 on 2021-07-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('talle', models.CharField(max_length=100, verbose_name='Talle')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talles',
        ),
        migrations.AddField(
            model_name='detalle',
            name='producto',
            field=models.ManyToManyField(related_name='get_detalle', to='productos.Producto'),
        ),
    ]
