# Generated by Django 2.2.10 on 2021-10-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Titulo de la Portada')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Subtitulo de la Portada')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Precio del Título')),
                ('button', models.CharField(default='Compre Ahora', max_length=20, verbose_name='Boton de la Portada')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portadas', verbose_name='Imagen de Presentación')),
                ('priority', models.IntegerField(default=5, verbose_name='Orden de Prioridades')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('visibility', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portada',
                'verbose_name_plural': 'Portadas',
                'ordering': ['priority', 'date_created'],
            },
        ),
        migrations.DeleteModel(
            name='Portada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
