# Generated by Django 2.2.10 on 2021-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20210727_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='talle',
        ),
        migrations.AddField(
            model_name='detalle',
            name='modelo',
            field=models.CharField(default='', max_length=100, verbose_name='Modelo'),
        ),
    ]
