# Generated by Django 2.2.10 on 2021-10-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20211015_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['priority'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='fecha_creacion',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='imagen_principal',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='orden',
            new_name='priority',
        ),
    ]
