# Generated by Django 2.2.10 on 2021-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210727_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='color',
        ),
        migrations.AddField(
            model_name='detalle',
            name='talle',
            field=models.CharField(default='', max_length=100, verbose_name='Talle'),
        ),
    ]
