# Generated by Django 2.2.10 on 2021-10-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20211015_1435'),
        ('productos', '0004_auto_20211015_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='DetalleProducto',
            new_name='ItemDetalle',
        ),
        migrations.RenameModel(
            old_name='ProductoImagen',
            new_name='ItemImagen',
        ),
    ]
