# Generated by Django 2.2.10 on 2020-06-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20200621_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
