# Generated by Django 2.2.10 on 2021-07-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20210727_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle',
            new_name='DetalleProducto',
        ),
    ]
