# Generated by Django 2.2.10 on 2021-07-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20210727_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalleproducto',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
