# Generated by Django 2.2.10 on 2021-10-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20211015_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetalle',
            old_name='producto',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemdetalle',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='itemdetalle',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='itemdetalle',
            old_name='talle',
            new_name='sizy',
        ),
        migrations.RenameField(
            model_name='itemimagen',
            old_name='producto',
            new_name='item',
        ),
    ]
