# Generated by Django 2.2.10 on 2021-10-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20211015_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['priority', 'date_created'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='categorias',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='fecha_creacion',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='fecha_modificacion',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='oferta',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='precio',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='precio_oferta',
            new_name='price_offer',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='orden',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='estado',
            new_name='visibility',
        ),
    ]
