# Generated by Django 2.2.10 on 2021-10-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20211015_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.CharField(default='20.000', max_length=100, verbose_name='Precio'),
        ),
    ]
