# Generated by Django 2.2.10 on 2020-06-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_auto_20200621_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False, verbose_name='Activo/Inactivo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.IntegerField(default=0, verbose_name='Precio Oferta'),
        ),
    ]
