# Generated by Django 2.2.10 on 2021-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen de Presentación'),
        ),
    ]
