# Generated by Django 2.2.10 on 2020-06-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20200622_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='portadas', verbose_name='Imagen de Presentación'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='subtitulo',
            field=models.CharField(max_length=100, verbose_name='Subtitulo de la Portada'),
        ),
        migrations.AlterField(
            model_name='portada',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo de la Portada'),
        ),
    ]
