# Generated by Django 2.2.10 on 2020-06-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_auto_20200622_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portada',
            old_name='imagen1',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='portada',
            name='boton',
            field=models.CharField(default='Compre Ahora', max_length=20, verbose_name='Boton de la Portada'),
        ),
    ]
