# Generated by Django 2.2.10 on 2020-06-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auto_20200622_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portada',
            name='imagen',
        ),
        migrations.AddField(
            model_name='portada',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='portadas', verbose_name='Imagen de Presentación'),
        ),
    ]
