# Generated by Django 2.2.10 on 2020-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_auto_20200622_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='categorias', verbose_name='Imagen de Presentación'),
        ),
    ]
