# Generated by Django 2.2.10 on 2020-06-23 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_categoria_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False, verbose_name='En Ofertao/Precio Normal'),
        ),
    ]
