# Generated by Django 2.2.10 on 2020-06-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_auto_20200623_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
