# Generated by Django 2.2.10 on 2020-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20200624_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
    ]
