# Generated by Django 2.2 on 2020-07-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_portada_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False, verbose_name='En Oferta/Precio Normal'),
        ),
    ]
