# Generated by Django 2.2.10 on 2020-12-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_auto_20200705_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Modelo', models.CharField(max_length=100, verbose_name='Talle')),
            ],
            options={
                'verbose_name': 'Talle',
                'verbose_name_plural': 'Talles',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Imagén'),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
    ]
