# Generated by Django 2.2.10 on 2020-12-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_auto_20201203_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen3',
        ),
    ]
