# Generated by Django 2.2.10 on 2020-12-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_auto_20201203_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portada',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria',
            new_name='categorias',
        ),
    ]
