# Generated by Django 2.2.10 on 2020-12-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_auto_20201203_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelos',
            field=models.CharField(default='Modelos entre comas', max_length=255, verbose_name='Modelos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='talles',
            field=models.CharField(default='Talles entre comas', max_length=255, verbose_name='Talles'),
        ),
    ]
