# Generated by Django 2.2.10 on 2020-12-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_auto_20201205_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelos',
            field=models.CharField(blank=True, default='Modelos entre comas', max_length=255, null=True, verbose_name='Modelos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talles',
            field=models.CharField(blank=True, default='Talles entre comas', max_length=255, null=True, verbose_name='Talles'),
        ),
    ]
