# Generated by Django 2.2.10 on 2021-10-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('accounts', '0002_auto_20210105_2321'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Deseo',
                'verbose_name_plural': 'Lista de Deseos',
            },
        ),
    ]
