# Generated by Django 2.2.10 on 2021-10-12 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20211012_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Estado del Pedido', 'verbose_name_plural': 'Estado de los Pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 14, 42, 34, 426145), verbose_name='Fecha de Entrega'),
        ),
    ]
