# Generated by Django 2.2 on 2020-06-28 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200627_0212'),
        ('cart', '0006_auto_20200628_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
