# Generated by Django 2.2.10 on 2021-10-12 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20211012_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_by',
            field=models.CharField(default='', max_length=255, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking',
            field=models.CharField(default='', max_length=255, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 15, 8, 20, 699861), verbose_name='Fecha de Entrega'),
        ),
    ]
