# Generated by Django 2.2.10 on 2021-10-13 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20211012_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ManyToManyField(to='cart.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 14, 2, 48, 618087), verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('RE', 'Recibido'), ('EM', 'Empaquetado'), ('EC', 'En Camino'), ('LR', 'Listo Para Retirno'), ('PL', 'Problemas Logísticos')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
