# Generated by Django 2.2.10 on 2021-10-13 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20211013_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 14, 5, 20, 371518), verbose_name='Fecha de Entrega'),
        ),
    ]
