# Generated by Django 2.2.10 on 2021-10-13 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20211013_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='status',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 14, 22, 45, 429622), verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking',
            field=models.CharField(default='', max_length=255, verbose_name='Tracking'),
        ),
    ]
