# Generated by Django 2.2 on 2020-06-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Código'),
        ),
    ]
