# Generated by Django 2.2.10 on 2021-10-14 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20211013_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 17, 13, 38, 29005), verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('RE', 'Recibido'), ('EM', 'Empaquetado'), ('EC', 'En Camino'), ('LR', 'Listo Para Retiro'), ('PL', 'Problemas Logísticos'), ('CA', 'Cancelado'), ('RE', 'Retirado')], default='PE', max_length=2, verbose_name='Estado'),
        ),
    ]
