# Generated by Django 2.2 on 2020-06-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20200629_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Descuento Fijo'),
        ),
    ]
