# Generated by Django 2.2.10 on 2021-10-15 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20211014_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 14, 7, 28, 603460), verbose_name='Fecha de Entrega'),
        ),
    ]
