# Generated by Django 2.2 on 2020-06-29 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20200629_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
    ]
