# Generated by Django 2.2.10 on 2021-10-15 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20211015_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='producto',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='producto',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 14, 33, 42, 198379), verbose_name='Fecha de Entrega'),
        ),
    ]
