# Generated by Django 2.2 on 2020-06-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20200629_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Articulo Pedido', 'verbose_name_plural': 'Articulos Pedidos'},
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
