# Generated by Django 2.2.10 on 2021-10-15 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20211015_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 14, 45, 23, 148297), verbose_name='Fecha de Entrega'),
        ),
    ]
