# Generated by Django 2.2 on 2020-06-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20200629_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupon', 'verbose_name_plural': 'Cupones'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
