# Generated by Django 2.2.10 on 2021-10-18 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20211015_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 21, 16, 29, 11, 198981), verbose_name='Fecha de Entrega'),
        ),
    ]
