# Generated by Django 2.2 on 2020-07-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20200629_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Descuento Fijo'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porcentaje'),
        ),
    ]
