# Generated by Django 2.2 on 2020-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20200701_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Descuento Fijo'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='Porcentaje'),
        ),
    ]
