# Generated by Django 2.2 on 2020-07-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20200701_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total a Pagar'),
        ),
    ]
