# Generated by Django 2.2.10 on 2023-06-28 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_auto_20230627_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 23, 16, 18, 182021), verbose_name='Fecha de Entrega'),
        ),
    ]
