# Generated by Django 2.2.10 on 2024-06-23 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20230627_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 17, 28, 0, 906801), verbose_name='Fecha de Entrega'),
        ),
    ]
