# Generated by Django 2.2 on 2020-07-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20200701_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
    ]
