# Generated by Django 2.2 on 2020-07-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_coupon_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PRO', 'Proceso'), ('FI', 'Finalizado')], default='PE', max_length=2),
        ),
    ]
