# Generated by Django 2.2.10 on 2020-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'Proceso'), ('FI', 'Finalizado')], default='PE', max_length=2),
        ),
    ]
