# Generated by Django 2.2.10 on 2020-12-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_auto_20200808_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='model',
            field=models.CharField(default='Vacio', max_length=255, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Vacio', max_length=255, verbose_name='Talle'),
        ),
    ]
