# Generated by Django 2.2.10 on 2021-01-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, verbose_name='Categoria del Email')),
                ('email', models.EmailField(max_length=100, verbose_name='Dirección de Correo Electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correo Electronico',
                'verbose_name_plural': 'Correos Electronicos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('fact', models.CharField(max_length=100, verbose_name='Tipo de Dato')),
                ('value', models.CharField(max_length=100, verbose_name='Texto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100, verbose_name='Categoria del Número')),
                ('number', models.CharField(max_length=12, verbose_name='Número de Contacto')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Tiene WhatsApp/No tiene')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('social', models.CharField(max_length=100, verbose_name='Nombre de la Red Social')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL de la red Social')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['-social'],
            },
        ),
    ]
