# Generated by Django 2.2.10 on 2020-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200621_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'ordering': ['-tipo'],
            },
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='URL de la red Social'),
        ),
    ]
