# Generated by Django 2.2 on 2020-06-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200622_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, verbose_name='Dirección de Correo Electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correo Electronico',
                'verbose_name_plural': 'Correos Electronicos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('fact', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
                'ordering': ['-fact'],
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=13, verbose_name='Número de Contacto')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Tiene WhatsApp/No tiene')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Dato',
        ),
    ]
