# Generated by Django 2.2 on 2020-06-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200630_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('social', models.CharField(max_length=100, verbose_name='Nombre de la Red Social')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL de la red Social')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['-social'],
            },
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['id'], 'verbose_name': 'Dato', 'verbose_name_plural': 'Datos'},
        ),
        migrations.AlterField(
            model_name='fact',
            name='fact',
            field=models.CharField(max_length=100, verbose_name='Tipo de Dato'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Texto'),
        ),
    ]
