# Generated by Django 2.2 on 2020-06-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200630_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['-social'], 'verbose_name': 'Red Social', 'verbose_name_plural': 'Redes Sociales'},
        ),
    ]
