# Generated by Django 2.2 on 2020-07-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_email_fact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='fact',
            new_name='category',
        ),
    ]
