# Generated by Django 2.2 on 2020-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_number_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=12, verbose_name='Número de Contacto'),
        ),
    ]
